[package]
name = "neolink"
version = "0.1.0"
authors = ["George Hilliard <thirtythreeforty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory = "0.3.1"
crossbeam-utils = "0.7"
env_logger = "*"
err-derive = "0.2.4"
gstreamer = "0.15"
gstreamer-app = "0.15"
gstreamer-player = "0.15"
gstreamer-rtsp-server = "0.15"
log = { version = "0.4.8", features = ["release_max_level_warn"] }
indoc = "0.3.5"
md5 = "0.7.0"
nom = "5.1.1"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
toml = "0.5"
yaserde = { git = "https://github.com/media-io/yaserde.git" }
yaserde_derive = { git = "https://github.com/media-io/yaserde.git" }
xml-rs = "0.8.2"
