# A bind value of 0.0.0.0 means any network this computer can access
# You can chage this to a specfic network e.g. "192.168.1.101" here
# Or to no networks e.g. this computer only "127.0.0.1"
bind = "0.0.0.0"

# Default port is 8554 but you can change it by uncommenting the following
# bind_port = 8554

# Uncomment the following and supply a path to a valid PEM
# to activate TLS encryption.
# The PEM should contain the certificate and the private key
# If TLS is activated you must connect with "rtsps://" and not "rtsp://"
# certificate = "/path/to/pem/with/cert/and/key"

# Choose if the client is required to provide a certificate signed by the server's CA.
# none|requested|required - default none
# tls_client_auth = "required"

# You can password protect the rtsp server mount points by adding users
# like the following me and someone. If you do not add [[users]]
# then anyone can connect without a password or username
# To access such a stream try using a url such as "rtsp://me:mepass@192.168.1.101/driveway"

# [[users]]
# name = "me"
# pass = "mepass"
#
# [[users]]
# name = "someone"
# pass = "someonepass"


[[cameras]]
name = "driveway"
username = "admin"
password = "12345678"
address = "192.168.1.187:9000"
# mqtt.broker_addr = "192.168.1.122"
# mqtt.port = 1883
# mqtt.credentials = ["mqtt_user", "mqtt_password"]

# If you use a battery camera: **Instead** of an `address` supply the uid
# as follows
# uid = "ABCD01234567890EFG"

# By default any of the users can connect (or anyone at all if no users are specfied)
# You can uncomment the following to permit only specfic users
# permitted_users = [ "me" ]

# By default "both" "mainStream" and "subStream" are connected
# If your device has user connection limits try a single stream instead.
# stream = "mainStream"


[[cameras]]
name = "storage shed"
username = "admin"
password = "987654321"
address = "192.168.1.245:9000"
# If you use a battery camera: **Instead** of an `address` supply the uid
# as follows
# uid = "ABCD01234567890EFG"

# If you use an NVR that relays several camera connections you can choose which
# camera to connect to with by setting the `channel_id`
#
# By default channel_id = 0. Eg the first connected camera on the device
# **Note**: that unlike in the offical client the  numbering starts from 0 not 1.
# An 8 channel NVR would have channels 0 through 7
# channel_id = 0
